"""
LangGraph ReAct agent for scientific literature research.
Uses ChatOllama (via langchain-ollama) as the backbone LLM with tool-calling.
Falls back to a sequential pipeline if Ollama is unavailable.
"""
import json
from langgraph.prebuilt import create_react_agent
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_ollama import ChatOllama

from backend.core.config import settings
from backend.core.logger import get_logger
from backend.agents.state import AgentState
from backend.agents.tools import (
    search_papers, summarize_paper,
    detect_contradictions, generate_overview,
    reset_cache, get_cache,
)
from backend.agents.prompts import SYSTEM_PROMPT

logger = get_logger(__name__)

TOOLS = [search_papers, summarize_paper, detect_contradictions, generate_overview]


def _build_graph():
    llm = ChatOllama(
        model=settings.ollama_model,
        base_url=settings.ollama_base_url,
        temperature=0.3,
    ).bind_tools(TOOLS)

    def agent_node(state: AgentState):
        msgs = [SystemMessage(content=SYSTEM_PROMPT)] + state["messages"]
        response = llm.invoke(msgs)
        return {"messages": [response], "step_count": state.get("step_count", 0) + 1}

    from langgraph.prebuilt import ToolNode
    tool_node = ToolNode(TOOLS)

    def should_continue(state: AgentState):
        last = state["messages"][-1]
        if hasattr(last, "tool_calls") and last.tool_calls:
            return "tools"
        return END

    graph = StateGraph(AgentState)
    graph.add_node("agent", agent_node)
    graph.add_node("tools", tool_node)
    graph.set_entry_point("agent")
    graph.add_conditional_edges("agent", should_continue)
    graph.add_edge("tools", "agent")
    return graph.compile()


def run_agent(query: str, max_per_source: int = 5, sources: list[str] | None = None) -> dict:
    """
    Run the full ReAct agent for a research query.
    Returns a dict with papers, summaries, contradictions, overview.
    Falls back to sequential pipeline if Ollama is not reachable.
    """
    reset_cache()
    sources_str = ",".join(sources or ["arxiv", "semantic_scholar"])

    try:
        graph = _build_graph()
        initial_message = (
            f"Research the topic: '{query}'\n"
            f"1. Call search_papers with query='{query}', max_results={max_per_source}, sources='{sources_str}'\n"
            f"2. Call summarize_paper for each of the top 3-5 papers\n"
            f"3. Call detect_contradictions with all summarized paper IDs\n"
            f"4. Call generate_overview with query='{query}'"
        )
        state = {
            "query": query,
            "messages": [HumanMessage(content=initial_message)],
            "papers": [],
            "summaries": {},
            "findings": [],
            "contradictions": [],
            "overview": None,
            "step_count": 0,
        }
        graph.invoke(state, config={"recursion_limit": 30})
    except Exception as e:
        logger.warning(f"LangGraph agent failed ({e}), falling back to sequential pipeline")
        _sequential_fallback(query, max_per_source, sources_str)

    cache = get_cache()
    return {
        "query": query,
        "papers": list(cache["papers"].values()),
        "summaries": cache["summaries"],
        "contradictions": cache["contradictions"],
        "overview": cache["summaries"].get("__overview__", _get_last_overview()),
    }


def _get_last_overview() -> str:
    """Extract overview generated by generate_overview tool if stored in cache."""
    from backend.agents.tools import _cache
    # The generate_overview tool returns the text directly — we grab it from the last tool result
    return _cache.get("__overview__", "")


def _sequential_fallback(query: str, max_per_source: int, sources_str: str):
    """Run tools without LangGraph when Ollama is unavailable. Summaries run in parallel."""
    from concurrent.futures import ThreadPoolExecutor, as_completed
    logger.info("Running sequential fallback pipeline")
    result = search_papers.invoke({"query": query, "max_results": max_per_source, "sources": sources_str})
    logger.info(f"Search result: {result[:100]}")

    cache = get_cache()
    paper_ids = list(cache["papers"].keys())[:5]

    # Summarize all papers in parallel
    with ThreadPoolExecutor(max_workers=5) as pool:
        futs = {pool.submit(summarize_paper.invoke, {"paper_id": pid}): pid for pid in paper_ids}
        for f in as_completed(futs):
            try:
                f.result()
            except Exception as e:
                logger.warning(f"Summary failed for {futs[f]}: {e}")

    if len(paper_ids) >= 2:
        detect_contradictions.invoke({"paper_ids": ",".join(paper_ids)})

    overview = generate_overview.invoke({"query": query})
    cache["__overview__"] = overview
